---
- hosts: target
  become: true
  tasks:
    - name: install nginx
      dnf:
         name: nginx
         state: latest
         update_cache: yes
    - name: start nginx
      service:
         name: nginx
         state: started
         enabled: yes
