---
- hosts: target
  become: true
  tasks:
    - name: Stopping MySQL server
      service:
        name: mysqld
        state: stopped
        enabled: yes

    - name: Removing MySQL server
      dnf:
        name: mysql-server
        state: removed
        update_cache: yes

- hosts: target
  become: true
  tasks:
    - name: stopping nginx
      service:
         name: nginx
         state: stopped
         enabled: yes

    - name: removing nginx
      dnf:
         name: nginx
         state: removed
         update_cache: yes

- hosts: target
  become: true
  tasks:
    - name: Stopping apache
      service:
        name: httpd
        state: stopped
        enabled: yes


    - name: Removing apache, epel-release, python3 and wget
      dnf:
        name: ["httpd","epel-release","wget","python3"]
        state: removed
        update_cache: yes
 
